In [31]:
import pandas as pd

In [32]:
an=pd.read_csv("adult_new.csv")

In [33]:
an.head()


age         workclass  fnlwgt     education  educational-num  \
0   28         Local-gov  336951    Assoc-acdm               12   
1   44           Private  160323  Some-college               10   
2   63  Self-emp-not-inc  104626   Prof-school               15   
3   65           Private  184454       HS-grad                9   
4   48           Private  279724       HS-grad                9   

       marital-status         occupation relationship   race gender  \
0  Married-civ-spouse    Protective-serv      Husband  White   Male   
1  Married-civ-spouse  Machine-op-inspct      Husband  Black   Male   
2  Married-civ-spouse     Prof-specialty      Husband  White   Male   
3  Married-civ-spouse  Machine-op-inspct      Husband  White   Male   
4  Married-civ-spouse  Machine-op-inspct      Husband  White   Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0             0             0              40  United-States   >50K  
1          7688             0              40  United-States   >50K  
2          3103             0              32  United-States   >50K  
3          6418             0              40  United-States   >50K  
4          3103             0              48  United-States   >50K

In [34]:
an.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [35]:
an["income"].unique()

array(['>50K', '<=50K'], dtype=object)

In [36]:
for i in an.columns:
    print(f"unique values in column {i}:\n\n{an[i].unique()},\n")

unique values in column age:

[28 44 63 65 48 43 40 34 45 46 36 22 42 41 55 33 59 29 27 31 58 54 37 56
 39 51 50 52 47 24 64 53 35 32 30 68 57 66 49 38 61 73 26 23 25 62 90 60
 67 69 72 85 71 77 70 19 21 74 75 20 81 76 80 88 78 79 84 17 18 82 83 86
 87],

unique values in column workclass:

['Local-gov' 'Private' 'Self-emp-not-inc' 'State-gov' 'Self-emp-inc' '?'
 'Federal-gov' 'Without-pay' 'Never-worked'],

unique values in column fnlwgt:

[336951 160323 104626 ...  84661 310152 257302],

unique values in column education:

['Assoc-acdm' 'Some-college' 'Prof-school' 'HS-grad' 'Masters' 'Doctorate'
 'Bachelors' 'Assoc-voc' '9th' '10th' '7th-8th' '11th' '5th-6th' '1st-4th'
 '12th' 'Preschool'],

unique values in column educational-num:

[12 10 15  9 14 16 13 11  5  6  4  7  3  2  8  1],

unique values in column marital-status:

['Married-civ-spouse' 'Never-married' 'Divorced' 'Separated'
 'Married-AF-spouse' 'Widowed' 'Married-spouse-absent'],

unique values in column occupation:

['Pro

In [37]:
import numpy as np

In [38]:
an_new=an.replace("?",np.nan)

In [39]:
an_new.isnull().sum()

age                   0
workclass          1283
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         1288
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      508
income                0
dtype: int64

In [40]:
an_new.shape

(27414, 15)

In [41]:
1283/27414

0.04680090464726053

In [42]:
an_new["workclass"].fillna(an_new["workclass"].mode()[0],inplace=True)

In [43]:
an_new.isnull().sum()

age                   0
workclass             0
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         1288
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      508
income                0
dtype: int64

In [44]:
an_new["occupation"].fillna(an_new["occupation"].mode()[0],inplace=True)

In [45]:
an_new.isnull().sum()

age                  0
workclass            0
fnlwgt               0
education            0
educational-num      0
marital-status       0
occupation           0
relationship         0
race                 0
gender               0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     508
income               0
dtype: int64

In [46]:
an_new["native-country"].fillna(an_new["native-country"].mode()[0],inplace=True)

In [47]:
an_new.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [48]:
for i in an.columns:
    if an_new[i].dtypes=="object":
        an_new[i].fillna(an[i].mode()[0],inplace=True)
    else:
            an_new[i].fillna(an[i].mean(),inplace=True)

In [49]:
an_new.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [50]:
colname =[]
for x in an_new.columns:
    if an_new[x].dtype=='object':
        colname.append(x)
colname


['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native-country',
 'income']

In [51]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in colname:
    an_new[x]=le.fit_transform(an_new[x])
    
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('feature',x)
    print('mapping', le_name_mapping)

feature workclass
mapping {'Federal-gov': 0, 'Local-gov': 1, 'Never-worked': 2, 'Private': 3, 'Self-emp-inc': 4, 'Self-emp-not-inc': 5, 'State-gov': 6, 'Without-pay': 7}
feature education
mapping {'10th': 0, '11th': 1, '12th': 2, '1st-4th': 3, '5th-6th': 4, '7th-8th': 5, '9th': 6, 'Assoc-acdm': 7, 'Assoc-voc': 8, 'Bachelors': 9, 'Doctorate': 10, 'HS-grad': 11, 'Masters': 12, 'Preschool': 13, 'Prof-school': 14, 'Some-college': 15}
feature marital-status
mapping {'Divorced': 0, 'Married-AF-spouse': 1, 'Married-civ-spouse': 2, 'Married-spouse-absent': 3, 'Never-married': 4, 'Separated': 5, 'Widowed': 6}
feature occupation
mapping {'Adm-clerical': 0, 'Armed-Forces': 1, 'Craft-repair': 2, 'Exec-managerial': 3, 'Farming-fishing': 4, 'Handlers-cleaners': 5, 'Machine-op-inspct': 6, 'Other-service': 7, 'Priv-house-serv': 8, 'Prof-specialty': 9, 'Protective-serv': 10, 'Sales': 11, 'Tech-support': 12, 'Transport-moving': 13}
feature relationship
mapping {'Husband': 0, 'Not-in-family': 1, 'Other-r

In [52]:
an_new

age  workclass  fnlwgt  education  educational-num  marital-status  \
0       28          1  336951          7               12               2   
1       44          3  160323         15               10               2   
2       63          5  104626         14               15               2   
3       65          3  184454         11                9               2   
4       48          3  279724         11                9               2   
...    ...        ...     ...        ...              ...             ...   
27409   27          3  257302          7               12               2   
27410   40          3  154374         11                9               2   
27411   58          3  151910         11                9               6   
27412   22          3  201490         11                9               4   
27413   52          4  287927         11                9               2   

       occupation  relationship  race  gender  capital-gain  capital-loss  \
0              10             0     4       1             0             0   
1               6             0     2       1          7688             0   
2               9             0     4       1          3103             0   
3               6             0     4       1          6418             0   
4               6             0     4       1          3103             0   
...           ...           ...   ...     ...           ...           ...   
27409          12             5     4       0             0             0   
27410           6             0     4       1             0             0   
27411           0             4     4       0             0             0   
27412           0             3     4       1             0             0   
27413           3             5     4       0         15024             0   

       hours-per-week  native-country  income  
0                  40              38       1  
1                  40              38       1  
2                  32              38       1  
3                  40              38       1  
4                  48              38       1  
...               ...             ...     ...  
27409              38              38       0  
27410              40              38       1  
27411              40              38       0  
27412              20              38       0  
27413              40              38       1  

[27414 rows x 15 columns]

Machine Learning Pipeline (supervised)
# 1. import the libraries (compulsary)
# 2. Read the data ( compulsary)
# 3. Treatment of null values ( optional)
# 4. outliers (optional)
# 5. label encoding ( optional)
# 6. useful column identification ( manual, automated ) (optional)
# 7. divide x and y (compulsary)
# 8. train test split (compulsary)
# 9. model.fit (linear, logistic,knn,svm,decision trees) (compulsary)
# 10. Evaluation [if Ragression ---> RHSE and R-Squared // else Classification ----> confusion Matrix ( compulsary)

In [53]:
x =an_new.values[:,0:-1]

y = an_new.values[:,-1]
x
y

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [54]:
x.shape

(27414, 14)

In [55]:
y.shape

(27414,)

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(19189, 14)
(19189,)
(8225, 14)
(8225,)


In [63]:
from sklearn.linear_model import LogisticRegression
#Create a model object
classifier=LogisticRegression()

#train the model object
classifier.fit(x_train,y_train)

LogisticRegression()

In [64]:
y_pred=classifier.predict(x_test)
print(y_pred)
print(list(zip(y_test,y_pred)))

[1 0 0 ... 0 1 0]
[(1, 1), (1, 0), (1, 0), (1, 0), (1, 1), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 1), (1, 0), (1, 0), (1, 1), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 1), (0, 0), (1, 0), (1, 1), (1, 0), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


In [66]:
cfm=confusion_matrix(y_test,y_pred)
print(cfm)
print("Classification report:")
print(classification_report(y_test,y_pred))
acc=accuracy_score(y_test,y_pred)
print("Accuracy of the model: ",acc)

[[4396  311]
 [2371 1147]]
Classification report:
              precision    recall  f1-score   support

           0       0.65      0.93      0.77      4707
           1       0.79      0.33      0.46      3518

    accuracy                           0.67      8225
   macro avg       0.72      0.63      0.61      8225
weighted avg       0.71      0.67      0.64      8225

Accuracy of the model:  0.6739209726443769


In [ ]:
Adjusting the threshold
Logistic Regression
anikidalipinb Usacjus
# store the predicted probabilities
y_pred_prob = classifier.predict_proba(X_test)
print(y_pred_prob)
[94]
[(0.95831253 0.04168747]
[0.97501687 0.02498313]
[0.24364199 0.75635801]
.
[0.84253325 0.15746675]
[0.82784054 0.17215946]
[0.16188528 0.83811472]]
y_pred_class=[]
for value in y_pred_prob[:,1]:
if value > 0.4:
y_pred_class.append(1)
else:
y-pred-class.append(o)
print(y_pred_class)

In [67]:
#Adjusting the threshold

In [69]:
y_pred_prob = classifier.predict_proba(x_test)
print(y_pred_prob)

[[0.47474261 0.52525739]
 [0.57898928 0.42101072]
 [0.59365734 0.40634266]
 ...
 [0.607518   0.392482  ]
 [0.37241694 0.62758306]
 [0.60878894 0.39121106]]


In [73]:
y_pred_class=[]
for value in y_pred_prob[:,1]:
    if value > 0.4:
        y_pred_class.append(1)
    else:
        y_pred_class.append(0)
print(y_pred_class)

[1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 

In [79]:
for a in np.arange(0.4,0.61,0.01):
    predict_mine = np.where(y_pred_prob[:,1]>a,1,0)
    cfm = confusion_matrix(y_test,predict_mine)
    total_err = cfm[0,1]+cfm[1,0]
    print("Errors at threshold ", a, ":",total_err,", type 2 error :",
     cfm[1,0],", type 1 error:",cfm[0,1])

Errors at threshold  0.4 : 3488 , type 2 error : 1367 , type 1 error: 2121
Errors at threshold  0.41000000000000003 : 3383 , type 2 error : 1535 , type 1 error: 1848
Errors at threshold  0.42000000000000004 : 3231 , type 2 error : 1652 , type 1 error: 1579
Errors at threshold  0.43000000000000005 : 3130 , type 2 error : 1836 , type 1 error: 1294
Errors at threshold  0.44000000000000006 : 3011 , type 2 error : 1992 , type 1 error: 1019
Errors at threshold  0.45000000000000007 : 2960 , type 2 error : 2084 , type 1 error: 876
Errors at threshold  0.4600000000000001 : 2898 , type 2 error : 2145 , type 1 error: 753
Errors at threshold  0.4700000000000001 : 2816 , type 2 error : 2207 , type 1 error: 609
Errors at threshold  0.4800000000000001 : 2722 , type 2 error : 2310 , type 1 error: 412
Errors at threshold  0.4900000000000001 : 2686 , type 2 error : 2370 , type 1 error: 316
Errors at threshold  0.5000000000000001 : 2682 , type 2 error : 2371 , type 1 error: 311
Errors at threshold  0.510

In [77]:
for a in np.arange(0.4,0.61,0.01):
    predict_mine = np.where(y_pred_prob[:,1]>a,1,0)
    cfm = confusion_matrix(y_test,predict_mine)
    total_err = cfm[0,1]+cfm[1,0]
    print("Errors at threshold ", a, ":",total_err,", type 2 error :",
    cfm[1,0],", type 1 error:",cfm[0,1])

Errors at threshold  0.4 : 3488 , type 2 error : 1367 , type 1 error: 2121
Errors at threshold  0.41000000000000003 : 3383 , type 2 error : 1535 , type 1 error: 1848
Errors at threshold  0.42000000000000004 : 3231 , type 2 error : 1652 , type 1 error: 1579
Errors at threshold  0.43000000000000005 : 3130 , type 2 error : 1836 , type 1 error: 1294
Errors at threshold  0.44000000000000006 : 3011 , type 2 error : 1992 , type 1 error: 1019
Errors at threshold  0.45000000000000007 : 2960 , type 2 error : 2084 , type 1 error: 876
Errors at threshold  0.4600000000000001 : 2898 , type 2 error : 2145 , type 1 error: 753
Errors at threshold  0.4700000000000001 : 2816 , type 2 error : 2207 , type 1 error: 609
Errors at threshold  0.4800000000000001 : 2722 , type 2 error : 2310 , type 1 error: 412
Errors at threshold  0.4900000000000001 : 2686 , type 2 error : 2370 , type 1 error: 316
Errors at threshold  0.5000000000000001 : 2682 , type 2 error : 2371 , type 1 error: 311
Errors at threshold  0.510

In [85]:
from sklearn. linear_model import SGDClassifier
classifier = SGDClassifier("log_loss")
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
#print intercepts and coefficients
#print(classifier.intercept_)
#print(classifier.coef_)

In [95]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cfm=confusion_matrix(y_test,y_pred)
print(cfm)
print("Classification report:")
print("classification report y_test,y_pred")
acc=accuracy_score(y_test,y_pred)
print("Accuracy of the model: ",acc)

[[4378  329]
 [2371 1147]]
Classification report:
classification report y_test,y_pred
Accuracy of the model:  0.6717325227963525
